language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
  - NODE_ENV=test
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database product;' -U postgres
  - psql -c "CREATE USER fantastic WITH PASSWORD 'fantastic7';" -U postgres
  - npm install -g sequelize-cli
script:
  - npm run test
after_success:
  - npm run coveralls